<?php

namespace App\Support;

class PpdbDummyData
{
    public static function parents(): array
    {
        return [
            [
                'id' => 'PARENT-001',
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmad.fauzi@example.com',
                'phone' => '0812-3456-7890',
                'relationship' => 'Ayah',
                'address' => 'Bandung, Jawa Barat',
                'status' => 'active',
                'username' => 'orangtua',
            ],
            [
                'id' => 'PARENT-002',
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'phone' => '0811-2233-4455',
                'relationship' => 'Ayah',
                'address' => 'Jakarta Selatan',
                'status' => 'active',
                'username' => '081122334455',
            ],
            [
                'id' => 'PARENT-003',
                'name' => 'Siti Aminah',
                'email' => 'siti.aminah@example.com',
                'phone' => '0813-9876-5432',
                'relationship' => 'Ibu',
                'address' => 'Cimahi, Jawa Barat',
                'status' => 'active',
                'username' => 'siswa',
            ],
            [
                'id' => 'PARENT-004',
                'name' => 'Hendra Wijaya',
                'email' => 'hendra.w@example.com',
                'phone' => '0856-1122-3344',
                'relationship' => 'Wali',
                'address' => 'Bandung Barat',
                'status' => 'active',
                'username' => 'calon',
            ],
            [
                'id' => 'PARENT-005',
                'name' => 'Rina Marlina',
                'email' => 'rina.marlina@example.com',
                'phone' => '0812-9988-7766',
                'relationship' => 'Ibu',
                'address' => 'Kabupaten Bandung',
                'status' => 'active',
                'username' => '1234567890',
            ],
        ];
    }

    public static function admins(): array
    {
        return [
            [
                'id' => 'ADM-001',
                'name' => 'Panitia PPDB Utama',
                'email' => 'admin@alazhar-sbp.sch.id',
                'role' => 'Super Admin',
                'phone' => '0811-2233-4455',
                'status' => 'active',
                'username' => 'admin',
            ],
            [
                'id' => 'ADM-002',
                'name' => 'Siti Nur Aisyah',
                'email' => 'panitia@alazhar-sbp.sch.id',
                'role' => 'Verifikator',
                'phone' => '0812-1111-2222',
                'status' => 'active',
                'username' => 'panitia',
            ],
            [
                'id' => 'ADM-003',
                'name' => 'Budi Setiawan',
                'email' => 'budi.admin@alazhar-sbp.sch.id',
                'role' => 'Keuangan',
                'phone' => '0813-5555-6666',
                'status' => 'active',
                'username' => 'keuangan',
            ]
        ];
    }

    public static function students(): array
    {
        return [
            [
                'id' => 'STU-001',
                'registration_id' => 'REG-2026-001',
                'parent_id' => 'PARENT-001',
                'name' => 'Ahmad Zaki Pratama',
                'nisn' => '1234567890',
                'gender' => 'Laki-laki',
                'birth_place' => 'Bandung',
                'birth_date' => '2012-05-14',
                'level' => 'SMP',
                'program' => 'SMP Reguler',
                'previous_school' => 'SD Islam Al Falah',
            ],
            [
                'id' => 'STU-002',
                'registration_id' => 'REG-2026-002',
                'parent_id' => 'PARENT-002',
                'name' => 'Aisyah Nur Haliza',
                'nisn' => '2345678901',
                'gender' => 'Perempuan',
                'birth_place' => 'Jakarta',
                'birth_date' => '2015-08-20',
                'level' => 'SD',
                'program' => 'SD Reguler',
                'previous_school' => 'TK Al Hidayah',
            ],
            [
                'id' => 'STU-003',
                'registration_id' => 'REG-2026-003',
                'parent_id' => 'PARENT-003',
                'name' => 'Rafika Al Farizi',
                'nisn' => null,
                'gender' => 'Laki-laki',
                'birth_place' => 'Cimahi',
                'birth_date' => '2020-02-10',
                'level' => 'TK B',
                'program' => 'TK B Reguler',
                'previous_school' => 'PG Al Amin',
            ],
            [
                'id' => 'STU-004',
                'registration_id' => 'REG-2026-004',
                'parent_id' => 'PARENT-004',
                'name' => 'Nayla Putri Ramadhani',
                'nisn' => null,
                'gender' => 'Perempuan',
                'birth_place' => 'Bandung Barat',
                'birth_date' => '2021-11-05',
                'level' => 'TK A',
                'program' => 'TK A Reguler',
                'previous_school' => null,
            ],
            [
                'id' => 'STU-005',
                'registration_id' => 'REG-2026-005',
                'parent_id' => 'PARENT-005',
                'name' => 'Arkan Daffa Pratama',
                'nisn' => '3456789012',
                'gender' => 'Laki-laki',
                'birth_place' => 'Bandung',
                'birth_date' => '2011-12-15',
                'level' => 'SMP',
                'program' => 'SMP Reguler',
                'previous_school' => 'SDN 1 Bandung',
            ],
            [
                'id' => 'STU-006',
                'registration_id' => 'REG-2026-006',
                'parent_id' => 'PARENT-001',
                'name' => 'Fathia Zahra',
                'nisn' => '4567890123',
                'gender' => 'Perempuan',
                'birth_place' => 'Bandung',
                'birth_date' => '2009-03-22',
                'level' => 'SMA',
                'program' => 'SMA IPA',
                'previous_school' => 'SMPN 5 Bandung',
            ],
            [
                'id' => 'STU-007',
                'registration_id' => 'REG-2026-007',
                'parent_id' => 'PARENT-002',
                'name' => 'Bima Satria',
                'nisn' => null,
                'gender' => 'Laki-laki',
                'birth_place' => 'Jakarta',
                'birth_date' => '2022-06-18',
                'level' => 'PG',
                'program' => 'Playgroup',
                'previous_school' => null,
            ],
            [
                'id' => 'STU-008',
                'registration_id' => 'REG-2026-008',
                'parent_id' => 'PARENT-003',
                'name' => 'Citra Kirana',
                'nisn' => '5678901234',
                'gender' => 'Perempuan',
                'birth_place' => 'Cimahi',
                'birth_date' => '2014-09-30',
                'level' => 'SD',
                'program' => 'SD Reguler',
                'previous_school' => 'TK Mawar',
            ],
        ];
    }

    public static function registrations(): array
    {
        return [
            [
                'id' => 'REG-2026-001',
                'student_id' => 'STU-001',
                'parent_id' => 'PARENT-001',
                'registration_number' => 'PPDB-2026-0001',
                'student_name' => 'Ahmad Zaki Pratama',
                'level' => 'SMP',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '22 Mei 2025 10:15',
                'status' => 'Terverifikasi',
                'status_class' => 'verified',
                'payment_status' => 'Lunas',
                'document_status' => 'Lengkap',
                'selection_status' => 'Menunggu Tes',
            ],
            [
                'id' => 'REG-2026-002',
                'student_id' => 'STU-002',
                'parent_id' => 'PARENT-002',
                'registration_number' => 'PPDB-2026-0002',
                'student_name' => 'Aisyah Nur Haliza',
                'level' => 'SD',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '22 Mei 2025 09:48',
                'status' => 'Menunggu Verifikasi',
                'status_class' => 'waiting',
                'payment_status' => 'Belum Lunas',
                'document_status' => 'Menunggu Verifikasi',
                'selection_status' => 'Menunggu Verifikasi',
            ],
            [
                'id' => 'REG-2026-003',
                'student_id' => 'STU-003',
                'parent_id' => 'PARENT-003',
                'registration_number' => 'PPDB-2026-0003',
                'student_name' => 'Rafika Al Farizi',
                'level' => 'TK B',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '22 Mei 2025 09:30',
                'status' => 'Terverifikasi',
                'status_class' => 'verified',
                'payment_status' => 'Lunas',
                'document_status' => 'Lengkap',
                'selection_status' => 'Menunggu Observasi',
            ],
            [
                'id' => 'REG-2026-004',
                'student_id' => 'STU-004',
                'parent_id' => 'PARENT-004',
                'registration_number' => 'PPDB-2026-0004',
                'student_name' => 'Nayla Putri Ramadhani',
                'level' => 'TK A',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '22 Mei 2025 09:12',
                'status' => 'Menunggu Verifikasi',
                'status_class' => 'waiting',
                'payment_status' => 'Menunggu Konfirmasi',
                'document_status' => 'Belum Lengkap',
                'selection_status' => 'Menunggu Verifikasi',
            ],
            [
                'id' => 'REG-2026-005',
                'student_id' => 'STU-005',
                'parent_id' => 'PARENT-005',
                'registration_number' => 'PPDB-2026-0005',
                'student_name' => 'Arkan Daffa Pratama',
                'level' => 'SMP',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '22 Mei 2025 08:55',
                'status' => 'Ditolak',
                'status_class' => 'rejected',
                'payment_status' => 'Lunas',
                'document_status' => 'Ditolak',
                'selection_status' => 'Tidak Lolos Administrasi',
            ],
            [
                'id' => 'REG-2026-006',
                'student_id' => 'STU-006',
                'parent_id' => 'PARENT-001',
                'registration_number' => 'PPDB-2026-0006',
                'student_name' => 'Fathia Zahra',
                'level' => 'SMA',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '21 Mei 2025 14:20',
                'status' => 'Diterima',
                'status_class' => 'verified',
                'payment_status' => 'Lunas',
                'document_status' => 'Lengkap',
                'selection_status' => 'Diterima',
            ],
            [
                'id' => 'REG-2026-007',
                'student_id' => 'STU-007',
                'parent_id' => 'PARENT-002',
                'registration_number' => 'PPDB-2026-0007',
                'student_name' => 'Bima Satria',
                'level' => 'PG',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '21 Mei 2025 10:10',
                'status' => 'Draft',
                'status_class' => 'waiting',
                'payment_status' => 'Belum Lunas',
                'document_status' => 'Belum Upload',
                'selection_status' => 'Draft',
            ],
            [
                'id' => 'REG-2026-008',
                'student_id' => 'STU-008',
                'parent_id' => 'PARENT-003',
                'registration_number' => 'PPDB-2026-0008',
                'student_name' => 'Citra Kirana',
                'level' => 'SD',
                'wave' => 'Gelombang 1',
                'academic_year' => '2026/2027',
                'registered_at' => '20 Mei 2025 16:45',
                'status' => 'Cadangan',
                'status_class' => 'waiting',
                'payment_status' => 'Lunas',
                'document_status' => 'Lengkap',
                'selection_status' => 'Cadangan',
            ],
        ];
    }

    public static function documents(): array
    {
        return [
            [
                'id' => 'DOC-001',
                'registration_id' => 'REG-2026-001',
                'name' => 'Akta Kelahiran',
                'file_name' => 'akta-ahmad-zaki.pdf',
                'status' => 'Terverifikasi',
                'uploaded_at' => '22 Mei 2025 10:25',
                'verified_by' => 'Siti Nur Aisyah',
                'notes' => null,
            ],
            [
                'id' => 'DOC-002',
                'registration_id' => 'REG-2026-001',
                'name' => 'Kartu Keluarga',
                'file_name' => 'kk-ahmad-fauzi.pdf',
                'status' => 'Terverifikasi',
                'uploaded_at' => '22 Mei 2025 10:26',
                'verified_by' => 'Siti Nur Aisyah',
                'notes' => null,
            ],
            [
                'id' => 'DOC-003',
                'registration_id' => 'REG-2026-002',
                'name' => 'Kartu Keluarga',
                'file_name' => 'kk-aisyah.pdf',
                'status' => 'Menunggu Verifikasi',
                'uploaded_at' => '22 Mei 2025 09:50',
                'verified_by' => null,
                'notes' => null,
            ],
            [
                'id' => 'DOC-004',
                'registration_id' => 'REG-2026-004',
                'name' => 'Akta Kelahiran',
                'file_name' => 'akta-nayla.pdf',
                'status' => 'Revisi',
                'uploaded_at' => '22 Mei 2025 09:15',
                'verified_by' => 'Panitia PPDB Utama',
                'notes' => 'Scan buram, mohon upload ulang.',
            ],
        ];
    }

    public static function schedules(): array
    {
        return [
            [
                'id' => 'SCH-001',
                'title' => 'Tes Akademik SMP',
                'level' => 'SMP',
                'type' => 'Tes Akademik',
                'date' => '24 Mei 2025',
                'time' => '08.00 - 10.00 WIB',
                'location' => 'Ruang Kelas SMP 1',
                'status' => 'Terjadwal',
            ],
            [
                'id' => 'SCH-002',
                'title' => 'Observasi & Wawancara TK A',
                'level' => 'TK A',
                'type' => 'Observasi',
                'date' => '25 Mei 2025',
                'time' => '08.30 - 11.00 WIB',
                'location' => 'Area Bermain TK',
                'status' => 'Terjadwal',
            ],
            [
                'id' => 'SCH-003',
                'title' => 'Wawancara Orang Tua SMP',
                'level' => 'SMP',
                'type' => 'Wawancara Orang Tua',
                'date' => '24 Mei 2025',
                'time' => '10.30 - 12.00 WIB',
                'location' => 'Ruang Meeting 1',
                'status' => 'Terjadwal',
            ],
            [
                'id' => 'SCH-004',
                'title' => 'Psikotes SD',
                'level' => 'SD',
                'type' => 'Psikotes',
                'date' => '26 Mei 2025',
                'time' => '08.00 - 11.00 WIB',
                'location' => 'Aula Utama',
                'status' => 'Terjadwal',
            ],
            [
                'id' => 'SCH-005',
                'title' => 'Pengumuman Seleksi Gelombang 1',
                'level' => 'Semua',
                'type' => 'Pengumuman Seleksi',
                'date' => '30 Mei 2025',
                'time' => '10.00 WIB',
                'location' => 'Portal PPDB',
                'status' => 'Terjadwal',
            ],
        ];
    }

    public static function selectionResults(): array
    {
        return [
            [
                'registration_id' => 'REG-2026-006',
                'student_name' => 'Fathia Zahra',
                'level' => 'SMA',
                'academic_score' => 92,
                'interview_score' => 90,
                'document_score' => 95,
                'final_score' => 92.5,
                'result' => 'Diterima',
                'announcement_date' => '28 Mei 2025',
                'notes' => 'Lulus seleksi prestasi',
            ],
            [
                'registration_id' => 'REG-2026-001',
                'student_name' => 'Ahmad Zaki Pratama',
                'level' => 'SMP',
                'academic_score' => 86,
                'interview_score' => 88,
                'document_score' => 95,
                'final_score' => 89,
                'result' => 'Menunggu',
                'announcement_date' => '30 Mei 2025',
                'notes' => '-',
            ],
            [
                'registration_id' => 'REG-2026-005',
                'student_name' => 'Arkan Daffa Pratama',
                'level' => 'SMP',
                'academic_score' => null,
                'interview_score' => null,
                'document_score' => null,
                'final_score' => null,
                'result' => 'Tidak Diterima',
                'announcement_date' => '22 Mei 2025',
                'notes' => 'Tidak lolos administrasi berkas.',
            ],
        ];
    }

    public static function dashboardStats(): array
    {
        return [
            [
                'label' => 'Total Pendaftar', 
                'value' => '1.248', 
                'note' => '↑ 18% dari minggu lalu', 
                'tone' => 'blue', 
                'icon' => 'i-users'
            ],
            [
                'label' => 'Verifikasi Berkas', 
                'value' => '892', 
                'note' => '71,5% dari total pendaftar', 
                'tone' => 'green', 
                'icon' => 'i-checkfile'
            ],
            [
                'label' => 'Menunggu Verifikasi', 
                'value' => '256', 
                'note' => '20,5% dari total pendaftar', 
                'tone' => 'orange', 
                'icon' => 'i-clock'
            ],
            [
                'label' => 'Ditolak', 
                'value' => '100', 
                'note' => '8% dari total pendaftar', 
                'tone' => 'purple', 
                'icon' => 'i-x'
            ],
            [
                'label' => 'Diterima', 
                'value' => '–', 
                'note' => 'Belum ada pengumuman', 
                'tone' => 'sky', 
                'icon' => 'i-trophy'
            ],
        ];
    }

    public static function activities(): array
    {
        return [
            [
                'id' => 'ACT-001',
                'type' => 'verification',
                'message' => 'Verifikasi berkas pendaftar Ahmad Zaki Pratama',
                'sub_message' => 'oleh Siti Nur Aisyah',
                'time' => '10:15',
                'date' => '22 Mei 2025',
                'icon' => 'i-check',
                'color' => 'green',
            ],
            [
                'id' => 'ACT-002',
                'type' => 'upload',
                'message' => 'Dokumen diunggah oleh Aisyah Nur Haliza',
                'sub_message' => '(Kartu Keluarga)',
                'time' => '09:48',
                'date' => '22 Mei 2025',
                'icon' => 'i-cloud',
                'color' => 'blue',
            ],
            [
                'id' => 'ACT-003',
                'type' => 'schedule',
                'message' => 'Jadwal Tes Akademik untuk jenjang SMP diperbarui',
                'sub_message' => 'oleh Budi Santoso',
                'time' => '09:30',
                'date' => '22 Mei 2025',
                'icon' => 'i-calendar',
                'color' => 'blue',
            ],
            [
                'id' => 'ACT-004',
                'type' => 'announcement',
                'message' => 'Pengumuman "Lulus Seleksi Gelombang 1" diterbitkan',
                'sub_message' => 'oleh Panitia PPDB',
                'time' => '09:00',
                'date' => '22 Mei 2025',
                'icon' => 'i-megaphone',
                'color' => 'blue',
            ],
            [
                'id' => 'ACT-005',
                'type' => 'registration',
                'message' => 'Pendaftar baru: Rafika Al Farizi',
                'sub_message' => 'jenjang TK B',
                'time' => '08:45',
                'date' => '22 Mei 2025',
                'icon' => 'i-user',
                'color' => 'red',
            ],
        ];
    }

    public static function announcements(): array
    {
        return [
            [
                'id' => 'ANN-001',
                'title' => 'Informasi Tes Akademik SMP',
                'description' => 'Tes akan dilaksanakan pada 24 Mei 2025.',
                'date' => '22 Mei 2025',
                'target' => 'SMP',
                'status' => 'Published',
                'color' => 'blue',
            ],
            [
                'id' => 'ANN-002',
                'title' => 'Pengumuman Lulus Seleksi Gelombang 1',
                'description' => 'Hasil seleksi dapat dilihat pada menu Hasil Seleksi.',
                'date' => '20 Mei 2025',
                'target' => 'Semua',
                'status' => 'Published',
                'color' => 'green',
            ],
            [
                'id' => 'ANN-003',
                'title' => 'Jadwal Wawancara Orang Tua',
                'description' => 'Silakan cek jadwal wawancara di menu Jadwal & Seleksi.',
                'date' => '18 Mei 2025',
                'target' => 'Semua',
                'status' => 'Published',
                'color' => 'red',
            ],
            [
                'id' => 'ANN-004',
                'title' => 'Batas Akhir Pelunasan Administrasi',
                'description' => 'Paling lambat tanggal 31 Mei 2025 pukul 23:59.',
                'date' => '15 Mei 2025',
                'target' => 'Diterima',
                'status' => 'Published',
                'color' => 'orange',
            ],
            [
                'id' => 'ANN-005',
                'title' => 'Panduan Upload Dokumen Pendaftaran',
                'description' => 'Pastikan dokumen dalam format PDF maks 2MB.',
                'date' => '10 Mei 2025',
                'target' => 'Semua',
                'status' => 'Published',
                'color' => 'blue',
            ]
        ];
    }
}
